<a href="https://colab.research.google.com/github/dharineeshramtp2000/Iris-Flower-Type-Prediction-Logistic-Regression-/blob/master/Heart_Disease_Predictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import the Libraries

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Importing the Dataset. Here we use the dataset from [ML Data](https://www.mldata.io/datasets/).
![](https://www.gardendesign.com/pictures/images/900x705Max/site_3/iris-louisiana-black-gamecock-iris-beardless-louisiana-iris-shutterstock-com_12592.jpg)
---
The dataset consists of the following attriutes

1.   Sepal Length (cm)
2.   Sepal Width (cm)
3.   Petal Length (cm)
4.   Petal Width (cm)
5.   Nominal: Iris Setosa, Iris Versicolour, Iris Virginica. This is the predictor class







In [0]:
Dataset = pd.read_csv("iris_dataset.csv")
X = Dataset.iloc[:, :-1]
y = Dataset.iloc[:, -1]

Now lets feature scale our independent variables from our famous [scikit](https://scikit-learn.org/stable/) library

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X = sc_X.fit_transform(X)

Splitting the dataset into training and testing and performing a good shuffle of data

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.4, random_state = 42, shuffle = True)

Now lets define our Logistic Regression model.
Here we define Stochastic Average Descen algorithm based LR.
We can also use other methods like liblinear, LBFGS etc. as the dataset is small.

Feel free to use the [Documnetaton for Logistic Regression](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html)

In [32]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(max_iter=1000, random_state = 0, multi_class='ovr', solver='sag')
classifier.fit(X_train, y_train)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='ovr', n_jobs=None, penalty='l2', random_state=0,
                   solver='sag', tol=0.0001, verbose=0, warm_start=False)

Now lets predict with our test set

In [0]:
y_pred = classifier.predict(X_test)

Its time for evaluating our model.

![](https://www.thinkebiz.net/wp-content/uploads/2018/01/74228032_s.jpg)

---
Lets first predict how our model is fitting for our training set
We use the famous
1.   f1 score
2.   accuracy 
to evaluate the model





In [0]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score

In [35]:
acc_train = accuracy_score(y_train, classifier.predict(X_train))
f1_train = f1_score(y_train, classifier.predict(X_train), average= 'weighted')

print("Traing set results")
print("ACCURACY ---------------------->",acc_train)
print("F1 SCORE ---------------------->",f1_train)


Traing set results
ACCURACY ----------------------> 0.9222222222222223
F1 SCORE ----------------------> 0.9221829900518426


Now lets see how well is our model. So now lets evaluate with our test set 

In [36]:
acc_test = accuracy_score(y_test, y_pred)
f1_test = f1_score(y_test, y_pred, average= 'weighted')

print("Test set results")
print("ACCURACY ---------------------->",acc_test)
print("F1 SCORE ---------------------->",f1_test)

Test set results
ACCURACY ----------------------> 0.9166666666666666
F1 SCORE ----------------------> 0.9163003663003664


Now lets have our famous Confusion Matrix to visually understand.

In [37]:
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[23  0  0]
 [ 0 15  4]
 [ 0  1 17]]


Our model has worked well with our test set too.
The **accuaracy** and **f1 score** for both test and training set is good.
Its always to put a question and ask to ourselves that is this the best model?

---

Obvisouly not!
We can still achive our accuracy by changing our models, changing the independent variables, change the metrics and so on.
Its great that we have successfully implemented logistic regression with our fish species dataset.